apiVersion: v1
kind: Namespace
metadata:
  name: httpbin-consumer
  labels:
    istio.io/rev: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-consumer
  namespace: httpbin-consumer
  labels:
    app: httpbin-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin-consumer
  template:
    metadata:
      labels:
        app: httpbin-consumer
    spec:
      containers:
      - name: httpbin-consumer
        image: acrackintheice/httpbin-consumer:2
        env:
          - name: "URL"
            value: "http://httpbin.httpbin/status/200"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        resources:
          limits: 
            memory: 100Mi
            cpu: 50m
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: httpbin-consumer
  namespace: httpbin-consumer
spec:
  maxReplicas: 3
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  - resource:
      name: memory
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: httpbin-consumer
---